ignore = ["stone-brick", "steel-plate", "iron-plate", "copper-plate", "coal"]
gap = 5  # min 2
beltType = "express-"  # "" or "fast-" or "express-"
assembler = "assembling-machine-3"
inserter = "stack-inserter"
longInserter = "long-handed-inserter"
useBeacon = True  # gap min 3
assemblerMod = "speed-module-3"
assemblerModNum = 4
module = "speed-module"
craftSpeed = 1.25  # The craft speed of the assembler including the modules and beacons
